README.md

Add Jenkins CI build status/badge of the plugin master branch: https://ci.jenkins.io/job/Plugins/job/atlassian-jira-software-cloud-plugin/job/master/badge/

Add Jenkins CI build status

---

src/main/java/com/atlassian/jira/cloud/jenkins/buildinfo/client/model/Builds.java
src/main/java/com/atlassian/jira/cloud/jenkins/common/client/model/Properties.java
src/main/java/com/atlassian/jira/cloud/jenkins/common/client/model/package-info.java
src/main/java/com/atlassian/jira/cloud/jenkins/deploymentinfo/client/model/Deployments.java

Testing:
Sample Payload before submission (captured in debug mode):
```json
{
"deployments": [
{
"deploymentSequenceNumber": 19,
"updateSequenceNumber": 1564030805,
"issueKeys": [
"SYD-18",
"SYD-17"
],
"displayName": "#19",
"url": "http://localhost:8080/job/github-project/job/master/19/",
"description": "#19",
"lastUpdated": "2019-07-25T05:00:05.714Z",
"label": "#19",
"state": "successful",
"pipeline": {
"id": "github-project/master",
"displayName": "github-project/master",
"url": "http://localhost:8080/job/github-project/job/master/"
},
"environment": {
"id": "us-stg-1",
"displayName": "us-stg-1",
"type": "staging"
},
"schemaVersion": "1.0"
}
],
"properties": {
"source": "jenkins"
}
}
```

JENKINS-58545 Enrich payload with metadata

---

README.md
pom.xml

There are two changes in this PR:
- Update README file
- Bump version from alpha-3 to beta-1

Update README and plugin version

---

pom.xml
src/main/java/com/atlassian/jira/cloud/jenkins/common/client/JiraApi.java

There was a small error in one of the javadocs that was causing the following issue during release:

Fix javadocs

---

README.md
pom.xml

Reason: A new vulnerability was identified in the previous version.

Upgrade Jackson databind library

---

src/main/java/com/atlassian/jira/cloud/jenkins/buildinfo/pipeline/JiraSendBuildInfoStep.java
src/main/java/com/atlassian/jira/cloud/jenkins/buildinfo/service/JiraBuildInfoRequest.java
src/main/java/com/atlassian/jira/cloud/jenkins/buildinfo/service/JiraBuildInfoSenderImpl.java
src/main/resources/com/atlassian/jira/cloud/jenkins/buildinfo/pipeline/JiraSendBuildInfoStep/config.jelly
src/main/resources/com/atlassian/jira/cloud/jenkins/buildinfo/pipeline/JiraSendBuildInfoStep/config.properties
src/main/resources/com/atlassian/jira/cloud/jenkins/buildinfo/pipeline/JiraSendBuildInfoStep/help.html
src/test/java/com/atlassian/jira/cloud/jenkins/buildinfo/pipeline/JiraSendBuildInfoStepTest.java
src/test/java/com/atlassian/jira/cloud/jenkins/buildinfo/service/JiraBuildInfoSenderImplTest.java

Tested with unit tests + tested manually with these two snippets:
jiraSendBuildInfo site: 'lrajasekaran.atlassian.net', branch: 'TEST-26'
and
jiraSendBuildInfo site: 'lrajasekaran.atlassian.net', branch: env.BRANCH_NAME
**Updated snipped generator:**

Add branch to build snippet

---

pom.xml

Preparing for the GA release, i.e. removing beta from the version

JENKINS-59002 Publish GA release

---

README.md

The OAuth Credentials functionality has been been enabled for all JIra tenants. Therefore, I'm removing the EAP signup form the README file

JENKINS-59002 Update README

---

src/main/java/com/atlassian/jira/cloud/jenkins/provider/HttpClientProvider.java
src/test/java/com/atlassian/jira/cloud/jenkins/provider/HttpClientProviderTest.java

Add OkHttp UserAgent interceptor

Add OkHttp UserAgent interceptor

---

pom.xml

Reported security vulnerabilities in the current version.

Upgrade Jackson lib

---

src/main/java/com/atlassian/jira/cloud/jenkins/config/JiraCloudPluginConfig.java
src/main/java/com/atlassian/jira/cloud/jenkins/config/JiraCloudSiteConfig.java

Compatibility with https://github.com/jenkinsci/jenkins/pull/4944.

Avoid com.thoughtworks.xstream.annotations

---

pom.xml
src/main/java/com/atlassian/jira/cloud/jenkins/buildinfo/client/BuildPayloadBuilder.java
src/main/java/com/atlassian/jira/cloud/jenkins/buildinfo/client/model/JiraBuildInfo.java
src/main/java/com/atlassian/jira/cloud/jenkins/buildinfo/client/model/TestInfo.java
src/test/java/com/atlassian/jira/cloud/jenkins/buildinfo/client/BuildPayloadBuilderTest.java

I added support for sending information about test results (total, passed, failed, skipped) of build to Jira.
The org.jenkins-ci.plugins:junit:1.3 dependency scope had to be changed from "test" to "compile".

Send test info to Jira.

---

pom.xml

changed jenkins plugin version to release new version 1.4.0

changed Jenkins plugin version to 1.4.0 to realease new version

---

src/main/java/com/atlassian/jira/cloud/jenkins/deploymentinfo/service/ChangeLogIssueKeyExtractor.java
src/test/java/com/atlassian/jira/cloud/jenkins/deploymentinfo/service/ChangeLogIssueKeyExtractorTest.java

Preparing  for release 1.5.0

---

pom.xml

updated pom.xml with latest version

updated pom.xml with latest version

---

pom.xml
src/test/java/com/atlassian/jira/cloud/jenkins/deploymentinfo/pipeline/JiraSendDeploymentInfoStepTest.java

added changes to fix security vulnerability with credentials dependency

added changes to fix security vulnerability with credentials dependency

---

src/main/java/com/atlassian/jira/cloud/jenkins/buildinfo/freestyle/FreeStylePostBuildStep.java
src/main/java/com/atlassian/jira/cloud/jenkins/buildinfo/freestyle/package-info.java
src/main/java/com/atlassian/jira/cloud/jenkins/buildinfo/pipeline/JiraSendBuildInfoStep.java
src/main/java/com/atlassian/jira/cloud/jenkins/buildinfo/service/FreestyleBuildInfoRequest.java
src/main/java/com/atlassian/jira/cloud/jenkins/buildinfo/service/FreestyleBuildInfoSender.java
src/main/java/com/atlassian/jira/cloud/jenkins/buildinfo/service/FreestyleJiraBuildInfoSenderImpl.java
src/main/java/com/atlassian/jira/cloud/jenkins/buildinfo/service/JiraBuildInfoRequest.java
src/main/java/com/atlassian/jira/cloud/jenkins/buildinfo/service/JiraBuildInfoSenderImpl.java
src/main/java/com/atlassian/jira/cloud/jenkins/buildinfo/service/MultibranchBuildInfoRequest.java
src/main/java/com/atlassian/jira/cloud/jenkins/buildinfo/service/MultibranchBuildInfoSenderImpl.java
src/main/java/com/atlassian/jira/cloud/jenkins/common/factory/JiraSenderFactory.java
src/main/java/com/atlassian/jira/cloud/jenkins/common/service/FreestyleIssueKeyExtractor.java
src/main/java/com/atlassian/jira/cloud/jenkins/deploymentinfo/service/FreestyleChangeLogIssueKeyExtractor.java
src/main/java/com/atlassian/jira/cloud/jenkins/util/Constants.java
src/main/java/com/atlassian/jira/cloud/jenkins/util/FreestyleBranchNameIssueKeyExtractor.java
src/main/resources/com/atlassian/jira/cloud/jenkins/buildinfo/freestyle/FreeStylePostBuildStep/config.jelly
src/main/resources/com/atlassian/jira/cloud/jenkins/buildinfo/freestyle/FreeStylePostBuildStep/config.properties
src/main/resources/com/atlassian/jira/cloud/jenkins/buildinfo/freestyle/FreeStylePostBuildStep/help.html
src/test/java/com/atlassian/jira/cloud/jenkins/buildinfo/freestyle/FreeStylePostBuildStepTest.java
src/test/java/com/atlassian/jira/cloud/jenkins/buildinfo/service/FreestyleJiraBuildInfoSenderImplTest.java
src/test/java/com/atlassian/jira/cloud/jenkins/buildinfo/service/JiraBuildInfoSenderImplTest.java
src/test/java/com/atlassian/jira/cloud/jenkins/deploymentinfo/service/FreestyleChangeLogIssueKeyExtractorTest.java
src/test/java/com/atlassian/jira/cloud/jenkins/util/FreestyleBranchNameIssueKeyExtractorTest.java

Added changes to support sending Build Information of freestyle projects to Jira

added changes for sending freestyle project build information to Jira

---

CONTRIBUTE.md
README.md

- [ x ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ x ] Ensure that the pull request title represents the desired changelog entry
- [ x ] Please describe what you did
- [ x ] Link to relevant issues in GitHub or Jira
- [ x ] Link to relevant pull requests, esp. upstream and downstream changes
- [ x ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

add contribution hints and polish the README a bit

---

pom.xml

Update plugin developer list, remove myself from the list.

Update plugin developers list

---

pom.xml
src/main/java/com/atlassian/jira/cloud/jenkins/buildinfo/client/BuildsApi.java
src/main/java/com/atlassian/jira/cloud/jenkins/buildinfo/client/model/Commit.java
src/main/java/com/atlassian/jira/cloud/jenkins/buildinfo/client/model/Ref.java
src/main/java/com/atlassian/jira/cloud/jenkins/buildinfo/client/model/TestInfo.java
src/main/java/com/atlassian/jira/cloud/jenkins/buildinfo/service/JiraBuildInfoSenderImpl.java
src/main/java/com/atlassian/jira/cloud/jenkins/common/client/ApiUpdateFailedException.java
src/main/java/com/atlassian/jira/cloud/jenkins/common/client/JenkinsAppApi.java
src/main/java/com/atlassian/jira/cloud/jenkins/deploymentinfo/client/DeploymentsApi.java
src/main/java/com/atlassian/jira/cloud/jenkins/deploymentinfo/service/JiraDeploymentInfoSenderImpl.java
src/test/java/com/atlassian/jira/cloud/jenkins/buildinfo/service/FreestyleJiraBuildInfoSenderImplTest.java
src/test/java/com/atlassian/jira/cloud/jenkins/buildinfo/service/JiraBuildInfoSenderImplTest.java
src/test/java/com/atlassian/jira/cloud/jenkins/common/client/ClassPathReader.java
src/test/java/com/atlassian/jira/cloud/jenkins/common/client/JenkinsAppApiTest.java
src/test/java/com/atlassian/jira/cloud/jenkins/common/client/JenkinsAppRequestTest.java
src/test/java/com/atlassian/jira/cloud/jenkins/common/client/JenkinsAppRequestTestData.java
src/test/java/com/atlassian/jira/cloud/jenkins/deploymentinfo/service/JiraDeploymentInfoSenderImplTest.java
src/test/resources/com/atlassian/jira/cloud/jenkins/common/client/build.json
src/test/resources/com/atlassian/jira/cloud/jenkins/common/client/deployment.json

Wraps all build and deployment events to the Jenkins app into a JWT.
Tested the integration with the Forge app successfully.

ARC-1152 wrap request payload to the Jenkins app into a JWT

---

src/main/java/com/atlassian/jira/cloud/jenkins/buildinfo/client/BuildsApi.java
src/main/java/com/atlassian/jira/cloud/jenkins/common/client/BadRequestException.java
src/main/java/com/atlassian/jira/cloud/jenkins/common/client/JenkinsAppApi.java
src/main/java/com/atlassian/jira/cloud/jenkins/common/client/JenkinsAppEventRequest.java
src/main/java/com/atlassian/jira/cloud/jenkins/common/client/JenkinsAppRequest.java
src/main/java/com/atlassian/jira/cloud/jenkins/config/JiraCloudSiteConfig2.java
src/main/java/com/atlassian/jira/cloud/jenkins/deploymentinfo/client/DeploymentsApi.java
src/main/java/com/atlassian/jira/cloud/jenkins/ping/JenkinsAppPingRequest.java
src/main/java/com/atlassian/jira/cloud/jenkins/ping/PingApi.java
src/main/java/com/atlassian/jira/cloud/jenkins/ping/PingResponse.java
src/main/java/com/atlassian/jira/cloud/jenkins/ping/package-info.java
src/test/java/com/atlassian/jira/cloud/jenkins/common/client/JenkinsAppApiTest.java
src/test/java/com/atlassian/jira/cloud/jenkins/common/client/JenkinsAppRequestTest.java
src/test/java/com/atlassian/jira/cloud/jenkins/common/client/JenkinsAppRequestTestData.java
src/test/java/com/atlassian/jira/cloud/jenkins/config/JiraCloudSiteConfig2DescriptorTest.java
src/test/resources/com/atlassian/jira/cloud/jenkins/common/client/ping.json

Adds the "test settings" functionality to test the connection to the Jenkins app

Add "test settings" functionality to connect to Jenkins app

---

pom.xml

Update to the current developer name.

Fix: Update developers in pom.xml

---

.gitignore
.mvn/extensions.xml
.mvn/maven.config
Jenkinsfile
pom.xml
src/main/java/com/atlassian/jira/cloud/jenkins/buildinfo/freestyle/FreeStylePostBuildStep.java
src/main/java/com/atlassian/jira/cloud/jenkins/buildinfo/pipeline/JiraSendBuildInfoStep.java
src/main/java/com/atlassian/jira/cloud/jenkins/deploymentinfo/pipeline/JiraSendDeploymentInfoStep.java

Update this plugin to conform to the latest best practices for Jenkins plugins from the Jenkins archetype, including building/testing on Java 17/21.

Refresh plugin for August 2023

---

src/main/java/com/atlassian/jira/cloud/jenkins/config/ConfigManagementLink.java
src/main/java/com/atlassian/jira/cloud/jenkins/exceptions/JiraConnectionFailedException.java
src/main/java/com/atlassian/jira/cloud/jenkins/exceptions/package-info.java
src/main/resources/com/atlassian/jira/cloud/jenkins/configuration/config.jelly
src/main/webapp/config.css
src/main/webapp/config.js
src/test/java/com/atlassian/jira/cloud/jenkins/config/ConfigManagementLinkTest.java

**What's in this PR?**
Tidied up the config screen to return errors when failure occurs
Save data before validate data to avoid loss
** Next **
Review the "final" copy to make sure everything is all gravy

Config feedback

---

pom.xml

**What's in this PR?**
keep repo uptodate post release

tag version

---

src/main/resources/com/atlassian/jira/cloud/jenkins/configuration/config.jelly
src/main/webapp/config.css
src/main/webapp/config.js

**What's in this PR?**
Update build and deployment section with new copy and collapse it underneath a advanced options accordian.
Collapsed state
Open state

ARC-2768 advanced section
